### ISSUE TITLE
track if a field has been blurred, or change the meaning of the touched bool

### ISSUE THREAD

**Issue by uforic** [flexport/formula-one#106]
Looking at the feedback strategies, and trying out a couple different combinations, I wasn't able to get an error to show up _only if the field had been blurred_.

It looks like there, that on blur, we mark a field as touched.
https://github.com/flexport/formula-one/blob/master/src/Field.js#L81

It also looks like when the form state changes, we mark a field as touched:
https://github.com/flexport/formula-one/blob/063cf44a0e852d20f368706112851c0437676b27/src/formState.js#L41

In the example of typing an email address, it's kinda annoying to start showing an error message the second they type the first character. More likely, we want to show the error message when they've blurred.

Happy to try and take this on; the two approaches I was thinking about were:
- Change the meaning of touched, to represent has been blurrred, then the "Touched" feedback strategy would be look at touched or changed, not just touched. There would be a new feedback strategy called blurred.
- Less risky: track a new meta field called blurred, and set touched and blurred on this line: https://github.com/flexport/formula-one/blob/master/src/Field.js#L81

Have you found the need for this use case? Is there some way using meta strategies to accomplish this?

Cheers! The library has been working great so far for a form I am building.

**Comment by dmnd** [comment]
:+1: I've ran into this too. 

`FeedbackStrategy.Touched` is odd: conceptually it means `Or(Changed, Blurred)`, but the primitive `Blurred` doesn't exist. I agree `Blurred` should exist.

After that, I think we could even consider removing `Touched` since it'd simply be `Or(Changed, Blurred)`. But perhaps it's nice to have it prebaked so clients don't have to deal with combinators. See also #107.
